name: livel_application
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^4.0.1
  agora_rtm: ^0.9.11
  cloud_functions: ^1.1.0
  cloud_firestore: "^2.2.0"
  cupertino_icons: ^1.0.0
  firebase_core: "1.2.0"
  firebase_auth: ^1.2.0
  firebase_storage: ^8.1.0
  flutter_typeahead: ^3.1.3
  flutter_credit_card: ^2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  image_picker: ^0.7.5+3
  google_fonts: ^2.1.0
  provider: ^5.0.0
  permission_handler: ^8.0.0+2
  pedantic: ^1.11.0
  stripe_payment: ^1.1.1
  progress_dialog: ^1.2.2
  rating_bar: ^0.2.0
  path: ^1.8.0
  speech_to_text: ^4.2.1
  avatar_glow: ^2.0.1
  translator: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "images/logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/usa.png
    - images/uk.png
    - images/picture_1.png
    - images/picture_2.png
    - images/picture_3.png
    - images/trip_image.png
    - images/saly.png
    - images/saly2.png
    - images/swhere.png
    - images/logo.png
    - images/newimage.png
    - images/saly_22.png
    - images/unknown.jpg
    - images/saly_15.png
    - images/sign_up.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages